#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"ClusterClass"})
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  namespace: #@ data.values.NAMESPACE
spec:
  controlPlane:
    ref:
      name: tkg-vsphere-kcp
    machineInfrastructure:
      ref:
        name: tkg-vsphere-control-plane
  infrastructure:
    ref:
      name: tkg-vsphere-infrastructure
      namespace: #@ data.values.NAMESPACE
  workers:
    machineDeployments:
    #@overlay/match by="class"
    - class: tkg-worker
      template:
        bootstrap:
          ref:
            name: tkg-vsphere-md-0
            namespace: #@ data.values.NAMESPACE
        infrastructure:
          ref:
            name: tkg-vsphere-worker
            namespace: #@ data.values.NAMESPACE

    #@overlay/match by="class", missing_ok=True
    - class: tkg-worker-windows
      template:
        bootstrap:
          ref:
            name: tkg-vsphere-md-0
            namespace: #@ data.values.NAMESPACE
        infrastructure:
          ref:
            name: tkg-vsphere-worker
            namespace: #@ data.values.NAMESPACE

