apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: load-balancer-and-ingress-service.tanzu.vmware.com
  namespace: load-balancer-and-ingress-service
spec:
  refName: load-balancer-and-ingress-service.tanzu.vmware.com
  version: 1.7.3
  releaseNotes: "relevant release notes..."
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/load-balancer-and-ingress-service@sha256:a52f85a39dadae545777c933a8229d7412122bf5e8dd0fb6546031ea3af2c309
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
